# Generated by Django 5.1.2 on 2024-11-27 18:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickHouseSyncLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='clickhouse_sync',
                                              to='users.user')),
            ],
            options={
                'verbose_name': 'clickhouse_sync_log',
                'verbose_name_plural': 'clickhouse_sync_logs',
            },
        ),
    ]
